from TestCase import TestCase
from PullRequestInfo import PullRequestInfo
from pathlib import Path
import requests
import os
import sys
import builtins
import importlib.util
import inspect
from hypothesis.extra import ghostwriter
from MockDummy import MockDummy
import shutil

class TestCaseGenerator:
    def __init__(self):
        self.generated_test_cases = []

    def get_test_cases(self) -> list[TestCase]:
        return self.generated_test_cases
    
    def generate(self, pull_request_info: PullRequestInfo) -> list[TestCase]:
        pull_request = pull_request_info.get_pull_request()

        # create temp dir (contains files fetches from Github)
        # create out dir (will contain test files generated by ghostwriter)
        root_dir = Path(__file__).parent.parent
        temp_dir = root_dir / "temp_dir"
        out_dir = root_dir / "test_case_out"
        temp_dir.mkdir(exist_ok=True)
        out_dir.mkdir(exist_ok=True)

        # iterate through each file in pull request
        # fetch the content of the file and save it locally
        for file in pull_request.get_files():
            if file.filename.endswith(".py"):
                file_path = temp_dir / Path(file.filename).name

                response = requests.get(file.raw_url)
                response.raise_for_status()
                file_content = response.text

                file_path.write_text(file_content, encoding="utf-8")

        # generate the test cases for the files inside temp dir and save the result to out dir
        self.generate_all_test_cases(temp_dir, out_dir)

        # clean environment
        self._delete_dir(temp_dir)
        self._delete_dir(root_dir / "src" / ".hypothesis")

        return self.generated_test_cases
    
    def generate_all_test_cases(self, filepath_dir: Path, test_cases_output_dir: Path) -> None:
        # iterate through every file in the directory
        # then create & save the test for the file
        for filepath in filepath_dir.iterdir():
            if filepath.name.endswith(".py") and not "test" in filepath.name and not filepath.name.startswith("_"):
                print(f"Attempting to generate test case for {filepath}.....")
                self.generated_test_cases.append(TestCase(filepath.name, filepath))
                self.create_and_save_tests(filepath, test_cases_output_dir)
                print()
    
    def create_and_save_tests(self, file_path: Path, test_cases_output_dir: Path) -> None:        
        file_name = file_path.stem
        test_file_name = f"{file_name}_TEST"

        # generate test from file
        test_code = self.generate_tests_from_file(file_path)

        if not test_code.strip():
            print(f"No test cases generated!")
            return
        
        output_filepath = test_cases_output_dir / test_file_name

        self.generated_test_cases[-1].set_test(test_code)

        # save the generated tests into a file
        output_filepath.write_text(test_code, encoding="utf-8")

        print(f"Test case saved in {str(output_filepath)}")
 
    def generate_tests_from_file(self, file_path: Path) -> str:
        module = self._safe_import(file_path)

        if not module:
            return ""

        output = []

        # gets every objects/members of a module
        # if it's a function, pass it to ghostwriter to generate tests for that function
        for name, obj in inspect.getmembers(module):
            if inspect.isfunction(obj):
                try:
                    test_code = ghostwriter.fuzz(obj)
                    output.append(test_code)
                except Exception as e:
                    print(f"skip function {name}: {e}")
                
        print(f"Ghostwriter finished attempting to generate test code!")

        return "\n\n".join(output)
    
    def _safe_import(self, file_path: Path) -> str:
        # store the original mechanism to find what and how to load modules to the file
        original_import = builtins.__import__
        # store the original dictionary of imported module names
        original_modules = sys.modules.copy()
        print(f"original import and module temporarily overriden!")
        
        # create dummy imports for dependency modules
        builtins.__import__ = self._mock_import

        try:
            # create a module specification for a module in the file_path
            # contains all information for loading modules
            spec = importlib.util.spec_from_file_location("temp_module_spec", file_path.resolve())

            # create the dummy module from the spec
            module = importlib.util.module_from_spec(spec)

            # executes the module's source code
            spec.loader.exec_module(module)
            return module
        except Exception as e:
            print(f"skip import {file_path}: {e}")
            return None
        finally:
            # return the mechanism to load modules back to the original one
            builtins.__import__ = original_import
            # clear the imported modules in the environment
            sys.modules.clear()
            # update the environment with the original modules
            sys.modules.update(original_modules)
            print(f"original import and module fetched back.")

    def _mock_import(self, name, globals=None, locals=None, fromlist=(), level=0):
            # if environment doesn't have the dependency, then create a dummy module
            if name not in sys.modules:
                sys.modules[name] = MockDummy()
                print(f"Mock module created for {name}!")
            return sys.modules[name]
    
    def _delete_dir(self, directory: Path):
        if  directory.exists() and directory.is_dir():
            try:
                shutil.rmtree(str(directory))
            except OSError as e:
                print(f"Error deleting directory: {e.strerror}")
        else:
            print("Directory not found!")